CREATE TABLE IF NOT EXISTS `c4aqr_transaction` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `agent_id` int(11) NOT NULL,
  `MLS` varchar(20) NOT NULL,
  `transaction` varchar(20) NOT NULL,
  `transaction_type` varchar(25) NOT NULL,
  `listing_price` int(11) NOT NULL,
  `listing_date` date NOT NULL,
  `sold_price` int(20) NOT NULL,
  `sold_date` date NOT NULL,
  `address` varchar(200) NOT NULL,
  `state` varchar(20) NOT NULL,
  `city` varchar(20) NOT NULL,
  `zip` int(10) NOT NULL,
  `buyer1Name` varchar(100) NOT NULL,
  `buyer2Name` varchar(100) NOT NULL,
  `buyersfulladdress` varchar(200) NOT NULL,
  `buyer_phone` int(20) NOT NULL,
  `buyers_Agent` varchar(100) NOT NULL,
  `buyers_agent_email` varchar(35) NOT NULL,
  `buyers_agent_phone` int(20) NOT NULL,
  `seller1Name` varchar(100) NOT NULL,
  `seller2Name` varchar(100) NOT NULL,
  `sellersfulladdress` varchar(200) NOT NULL,
  `seller_phone` int(20) NOT NULL,
  `seller_Agent` varchar(100) NOT NULL,
  `seller_agent_email` varchar(35) NOT NULL,
  `seller_agent_phone` int(20) NOT NULL,
  `closing_title_escrow` varchar(100) NOT NULL,
  `escrow_tran` varchar(100) NOT NULL,
  `title_full_ddress` varchar(200) NOT NULL,
  `title_phone` int(20) NOT NULL,
  `title_agent` varchar(100) NOT NULL,
  `title_email_address` varchar(35) NOT NULL,
  `commission_amount` int(20) NOT NULL,
  `commission_type` varchar(50) NOT NULL,
  `earnest_money_amount` int(20) NOT NULL,
  `earnest_money_held_by` varchar(100) NOT NULL,
  `home_warranty_provided` varchar(50) NOT NULL,
  `notes_for_broker_instructions` varchar(1000) NOT NULL,
  `agent_notes_for_transaction_Office` varchar(1000) NOT NULL,
  `upload_files` varchar(1000) NOT NULL,
  `status` varchar(20) NOT NULL,
  `is_approve` int(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;