INSERT INTO `#__edocman_configs` (`id`, `config_key`, `config_value`) VALUES
(1, 'option', 'com_edocman'),
(2, 'view', 'configuration'),
(3, 'documents_path', ''),
(4, 'load_jquery', '1'),
(5, 'load_twitter_bootstrap', '1'),
(6, 'twitter_bootstrap_version', '2'),
(7, 'access_level_inheritance', '0'),
(8, 'activate_multilingual_feature', '0'),
(9, 'activate_herachical_folder_structure', '1'),
(10, 'file_upload_method', '0'),
(11, 'allowed_file_types', 'doc, docx, ppt, pptx, pdf, zip, rar, png, zipx'),
(12, 'delete_file_when_document_deleted', '0'),
(13, 'hide_download_button', '0'),
(14, 'show_view_button', '1'),
(15, 'exts_for_view', 'pdf,png,jpg,gif,jepg'),
(16, 'max_file_size', '2'),
(17, 'max_filesize_type', '3'),
(18, 'require_admin_approve', '0'),
(19, 'category_thumb_width', '100'),
(20, 'category_thumb_height', '100'),
(21, 'document_thumb_width', '100'),
(22, 'document_thumb_height', '100'),
(23, 'date_format', 'm-d-Y'),
(24, 'day_for_new', '1'),
(25, 'downloads_to_hot', '100'),
(26, 'enable_rss', '0'),
(27, 'overwrite_existing_file', '0'),
(28, 'download_log', '0'),
(29, 'collect_downloader_information', '1'),
(30, 'download_type', '0'),
(31, 'process_plugin', '1'),
(32, 'show_uploader_name_in_document_mamangement', '0'),
(33, 'notification_emails', ''),
(34, 'download_notification', '0'),
(35, 'download_email_subject', 'Download notification'),
(36, 'download_email_body', 'Dear administrator\r\n\r\nUsers [USERNAME] has just downloaded document [DOCUMENT_TITLE] from your site. User IP is [USER_IP] .\r\n'),
(37, 'download_link_email_subject', 'Document Download Information'),
(38, 'download_link_email_body', 'Dear [NAME]\r\n\r\nYou requested to download document [DOCUMENT_TITLE] on our website. Please click on the link below to download the document\r\n\r\n[DOWNLOAD_LINK]. The link will only valid for 3 days.\r\n\r\nRegards,\r\n\r\nWebsite Administrator Team\r\n'),
(39, 'download_complete_message', 'Thanks for providing us your information. The document [DOCUMENT_TITLE] should be downloaded shortly. If download doesn''t start, you can click on the link below to download it\r\n\r\n[DOWNLOAD_LINK]\r\n\r\nRegards,\r\n\r\nWebsite Administrator Team'),
(40, 'download_complete_message_send_download_link', 'Thanks for providing us your information. Please check your email to get the download link.\r\n\r\nRegards,\r\n\r\nWebsite Administrator Team'),
(41, 'upload_notification', '1'),
(42, 'upload_email_subject', 'New document uploaded'),
(43, 'upload_email_body', 'Dear Administrator\r\n\r\nUser [USERNAME] has just uploaded new documents from front-end. Please login to back-end, check and publish the document.\r\n\r\nRegards,\r\n\r\nWebsite Administrator Team'),
(44, 'document_assigned_notification', '0'),
(45, 'document_assigned_email_subject', 'You have new document assigned'),
(46, 'document_assigned_email_body', 'Dear [NAME]\r\n\r\n[OWNER_NAME] has just assigned document [DOCUMENT_TITLE] to you. You can login, access and download the document.\r\n\r\nRegards,\r\n\r\nWebsite Administrator Team'),
(47, 'use_simple_upload_form', '1'),
(48, 'show_default_category_thumbnail', '0'),
(49, 'show_default_document_thumbnail', '0'),
(50, 'use_download_link_instead_of_detail_link', '1'),
(51, 'show_empty_cat', '1'),
(52, 'show_number_documents', '1'),
(53, 'number_categories_per_row', '2'),
(54, 'number_categories', '6'),
(55, 'show_subcategory_icon', '0'),
(56, 'show_subcategory_description', '0'),
(57, 'number_subcategories', '3'),
(58, 'number_documents', '5'),
(59, 'number_columns', '2'),
(60, 'show_detail_in_popup', '0'),
(61, 'show_publish_date', '1'),
(62, 'hide_details_button', '0'),
(63, 'show_sort_options', '1'),
(64, 'default_sort_option', 'tbl.ordering'),
(65, 'default_sort_direction', 'asc'),
(66, 'category_table_show_filetype', '1'),
(67, 'category_table_show_filesize', '1'),
(68, 'show_social_sharing_buttons', '1'),
(69, 'show_hits', '1'),
(70, 'show_filename', '1'),
(71, 'show_filesize', '1'),
(72, 'show_filetype', '1'),
(73, 'show_creation_date', '1'),
(74, 'show_modified_date', '1'),
(75, 'insert_document_id', '0'),
(76, 'insert_category_id', '0'),
(77, 'insert_category', '0'),
(78, 'task', 'save');